// EXERCICE 0
//faire une presentation sur les API en javascript et faire une presentation sur local storage et saission storage.

//exercice 1
//ECRIRE un PREGRAMME EN JAVSCRIPT QUI permet a l'utilisateur d'ajouter un etudiant dans un tableau grace a un systeme de curd.
// L'utilisateur ajoute les etudiants dans un tableau d'objet vide initialement declarer.L'utilisateur ajoute les informations de l'etudiant via un formulaire et chaque etudiant ajouter, sera afficher dans un tableau de taiwindcss 

//exercice 2
// creer un systeme de filtrage qui permet a l'utilisateur 

